# Generated by Django 4.2.1 on 2023-07-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regmodel',
        ),
    ]
